networks:
  image-builder:
    driver: bridge

volumes:
  mysql_data: {}
  redis_queue_data: {}

services: 
  redis-queue:
    image: redis:7.0-alpine
    container_name: image-builder-redis-queue-${ENVIRONMENT:-dev}
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - ${REDIS_PORT_FORWARD:-63792}:${REDIS_PORT:-6379}
    healthcheck:
      test: ["CMD-SHELL", "REDISCLI_AUTH=$REDIS_PASSWORD redis-cli -h localhost ping | grep PONG || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - redis_queue_data:/data
      - ./redis/redis-queue-developer.conf:/usr/local/etc/redis/redis.conf
    networks:
      - image-builder

  mysql:
    image: mysql:8.0
    container_name: image-builder-mysql-${ENVIRONMENT:-dev}
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - 3306
      - 33060
    ports:
      - ${DB_PORT_FORWARD:-3306}:${DB_PORT:-3306}
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -u $DB_USER --password=$DB_PASSWORD -P ${DB_PORT:-3306} ping | grep 'mysqld is alive' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - image-builder
