services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "${APP_PORT:-25565}:25565"
    environment:
      EULA: "TRUE"
    deploy:
      resources:
        limits:
          memory: 1.5G
    volumes:
      - "~/minecraft_data:/data"
