networks:
  image-builder:
    driver: bridge

volumes:
  mysql_data: {}
  redis_queue_data: {}

services:
  redis-queue:
    image: redis:7.0-alpine
    container_name: image-builder-redis-queue
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redis_queue_data:/data
      - ./redis/redis-queue-developer.conf:/usr/local/etc/redis/redis.conf
    networks:
      - image-builder
  wordpress:
    image: wordpress:latest
    ports:
      - 11:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
  mysql:
    image: mysql:8.0
    container_name: image-builder-mysql-${ENVIRONMENT:-dev}
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - ${DB_PORT_FORWARD:-3306}:${DB_PORT:-3306}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - image-builder
